// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqDVGhOY8_SqCJrnKDEyE80FN1VDMYio',
    appId: '1:170310918534:android:ab52fdbd0d5bb0721a0c07',
    messagingSenderId: '170310918534',
    projectId: 'technovation-2024-12-03',
    databaseURL: 'https://technovation-2024-12-03-default-rtdb.firebaseio.com',
    storageBucket: 'technovation-2024-12-03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSp-89B-vBXFRThafo3YKwEbddZczhtf0',
    appId: '1:170310918534:ios:13f86f50d4e5c9ed1a0c07',
    messagingSenderId: '170310918534',
    projectId: 'technovation-2024-12-03',
    databaseURL: 'https://technovation-2024-12-03-default-rtdb.firebaseio.com',
    storageBucket: 'technovation-2024-12-03.appspot.com',
    iosBundleId: 'com.example.litterApp',
  );
}
